# Generated by Django 5.2.8 on 2025-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Profesor Titular', 'Profesor Titular'), ('Profesor Auxiliar', 'Profesor Auxiliar'), ('Profesor Asistente', 'Profesor Asistente'), ('Profesor Instructor', 'Profesor Instructor')], max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('porciento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
