# Generated by Django 5.2.1 on 2025-11-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claustro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claustro',
            name='categoria_docente',
            field=models.CharField(blank=True, choices=[('titular', 'Profesor Titular'), ('auxiliar', 'Profesor Auxiliar'), ('asistente', 'Profesor Asistente'), ('instructor', 'Profesor Instructor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claustro',
            name='porciento',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='claustro',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='claustro',
            unique_together={('categoria_docente', 'fecha')},
        ),
        migrations.AlterModelOptions(
            name='claustro',
            options={'ordering': ['-fecha', 'categoria_docente']},
        ),
    ]
