# Generated by Django 5.2.8 on 2025-11-05 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('incentivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='area.area')),
                ('incentivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='incentivo.incentivo')),
            ],
        ),
    ]
