# Generated by Django 5.2.1 on 2025-11-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada')], default='pendiente', max_length=20),
        ),
    ]
