# Generated by Django 5.2.1 on 2025-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_especialista_rrhh',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es especialista de RRHH'),
        ),
    ]
