# Generated by Django 5.2.1 on 2025-11-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_es_especialista_rrhh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_especialista_rrhh',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_area_admin',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('jefe_area', 'Jefe de área'), ('especialista_rrhh', 'Especialista RRHH'), ('empleado', 'Empleado')], default='empleado', max_length=30),
        ),
    ]
