# Generated by Django 5.2.1 on 2025-11-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_es_especialista_rrhh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carga',
        ),
    ]
