# Generated by Django 5.2.1 on 2025-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_docente',
            field=models.CharField(blank=True, choices=[('titular', 'Profesor Titular'), ('auxiliar', 'Profesor Auxiliar'), ('asistente', 'Profesor Asistente'), ('instructor', 'Profesor Instructor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
