# Generated by Django 5.2.1 on 2025-11-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incentivo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
